"""empty message

Revision ID: 9a6f11b5dc89
Revises: ef22b5ad7e98
Create Date: 2024-05-20 15:01:03.989702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a6f11b5dc89'
down_revision = 'ef22b5ad7e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('avatar', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('signature', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_staff', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('is_staff')
        batch_op.drop_column('signature')
        batch_op.drop_column('avatar')
        batch_op.drop_column('_password')

    # ### end Alembic commands ###
